INSERT INTO Albums VALUES('ldk1', 'Leanderk','Életahalálelőtt','2017-09-22')
INSERT INTO Albums VALUES('ldk2', 'Leanderk','Luxusnyomor','2019-02-22')
INSERT INTO Tracks VALUES('Egy hónapja nem láttalak', '00:4:00', 'ldk1','AOYLgHjscbM')
INSERT INTO Tracks VALUES('Égjen Minden El', '00:3:35', 'ldk1','0OkE-sV1nlo')
INSERT INTO Tracks VALUES('Vigyetek kórházba', '00:3:53', 'ldk1','null')
INSERT INTO Tracks VALUES('Nem szól harang', '00:3:21', 'ldk1','null')
INSERT INTO Tracks VALUES('Ha elmész', '00:3:26', 'ldk1','null')
INSERT INTO Tracks VALUES('Fájdalom elvitelre', '00:3:47', 'ldk1','null')
INSERT INTO Tracks VALUES('Álarc', '00:3:07', 'ldk1','null')
INSERT INTO Tracks VALUES('Élet', '00:2:59', 'ldk1','null')
INSERT INTO Tracks VALUES('Lopott könyvek', '00:4:40', 'ldk1','null')
INSERT INTO Tracks VALUES('Egy napom maradt', '00:3:02', 'ldk1','null')
INSERT INTO Tracks VALUES('Luxusnyomor', '00:3:41', 'ldk2','u1CyvzKayz4')
INSERT INTO Tracks VALUES('Kell a háború', '00:3:45', 'ldk2','t5DTLCg-NrI')
INSERT INTO Tracks VALUES('Képtükör', '00:4:19', 'ldk2','null')
INSERT INTO Tracks VALUES('Aranymetszet', '00:3:12', 'ldk2','null')
INSERT INTO Tracks VALUES('A Ti dalotok', '00:3:55', 'ldk2','null')
INSERT INTO Tracks VALUES('Fraktálok', '00:4:04', 'ldk2','null')
INSERT INTO Tracks VALUES('Sötét én', '00:3:36', 'ldk2','null')
INSERT INTO Tracks VALUES('Úgy sírsz értem', '00:3:53', 'ldk2','null')
INSERT INTO Tracks VALUES('Hazavágyom', '00:3:52', 'ldk2','null')
INSERT INTO Tracks VALUES('Hull az elsárgult levél', '00:3:38', 'ldk2','null')
